"""Jett Medical brand tokens — single source of truth for document styling.

TODO(brand): the hex values below are placeholders. Replace with the real
Jett Medical palette (from the jett_automations brand assets) and drop the
logo at assets/jett_logo.png; pdf_writer picks it up automatically.
"""

WORDMARK = "JETT MEDICAL"

NAVY = "#1B2A4A"   # headers, wordmark band
TEAL = "#2AA5A0"   # accents, table rules
SLATE = "#4A5568"  # body text
LIGHT = "#F2F6F7"  # table striping

FONT_BODY = "Helvetica"
FONT_BOLD = "Helvetica-Bold"

DISCLAIMER = (
    "Generated by the Jett Marketing Agent from aggregate OSKA pipeline data. "
    "No patient-level information is contained in, or was used to produce, "
    "this document. For informational purposes only; not medical advice."
)
